version: '3.3'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/zeveze.ru.crt:/etc/nginx/ssl/zeveze.ru.crt
      - ./nginx/zeveze.ru.key:/etc/nginx/ssl/zeveze.ru.key
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  static_value:
  media_value: