### Omsk weather by coord

GET https://api.openweathermap.org/data/2.5/weather?lat=54.8863&lon=73&appid=<token>&units=metric&lang=ru
Content-Type: application/json


### Stupino weather by town

GET https://api.openweathermap.org/data/2.5/weather?q=Stupino&appid=<token>&units=metric&lang=ru
Content-Type: application/json
